
CC=clang-18
CXX=clang++-18
# no FC for clang
FC=
flags = -O3 -fstrict-aliasing
vecflags = -fvectorize
#-fslp-vectorize-aggressive
novecflags = -fno-vectorize
omp_flags=-fopenmp=libomp

ifdef VEC_REPORT
vecflags+=-fsave-optimization-record
#vecflags+=-mllvm -debug-only=loop-vectorize
#vecflags+=-Rpass-analysis=loop-vectorize
endif

ieee_math_flags+=
fast_math_flags+=-ffast-math

ifdef PRECISE_MATH
$(warning No 'precise' math flags for clang!)
endif

