CC=clang-18
CXX=clang++-18
# no FC for clang
FC=
flags = -O3 -fstrict-aliasing -g3 -fsave-optimization-record -fno-discard-value-names
vecflags = -fvectorize -fslp-vectorize
novecflags = -fno-vectorize
omp_flags=-fopenmp=libomp

ifdef VEC_REPORT
#vecflags+=-Rpass=loop-vectorize -Rpass-missed=loop-vectorize
#vecflags+=-mllvm -debug-only=loop-vectorize
#vecflags+=-Rpass-analysis=loop-vectorize
vecflags+=-Rpass=slp-vectorize -Rpass-missed=slp-vectorize
endif

ieee_math_flags+=
fast_math_flags+=-ffast-math

ifdef PRECISE_MATH
$(warning No 'precise' math flags for clang!)
endif
